name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  codeQuality:

    runs-on: ubuntu-latest
    env:
      ALCHEMY_PRIVATE_KEY: ${{ secrets.ALCHEMY_PRIVATE_KEY }}
      SEPOLIA_URL: ${{ secrets.SEPOLIA_URL }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
    
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: node ci --function installDeps
    
    - name: install python libs
      run: node ci --function installPythonLibs --params "{'libs':['crypto-py']}"

    - name: Run linter
      run: node ci --function lint

    - name: Run duplications check
      run: node ci --function checksDuplications

    - name: Run smart contracts unit tests
      run: node ci --function smartContractsUnitTest
    
    - name: Run scripts unit tests
      run: node ci --function scriptsUnitTest
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: nova-collective/agora
