name: tag

on:
    pull_request:
      branches:
        - master

jobs:
    tagVersion:
        if: github.event.pull_request.merged == 'true'
        runs-on: ubuntu-latest

        steps:
        - name: Tag the release with the version
          run: node ci --function tagRelease
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}