name: tag

on:
  push:
    branches:
      - main

jobs:
  tagVersion:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
    
    - name: Set up Git
      run: |
        git config --global user.name "Christian Palazzo"
        git config --global user.email "palazzochristian@yahoo.it"

    - name: Tag the release with the version
      run: node ci --function tagRelease
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}