name: tag

on:
  push:
    branches:
      - main

jobs:
  tagVersion:
    runs-on: ubuntu-latest

    steps:
    - uses: tibdex/github-app-token@v1
      id: get_app_token
      with: 
        app_id: ${{ vars.GH_ACTIONS_BOT_APP_ID }}
        private_key: ${{ secrets.GH_ACTIONS_BOT_PRIVATE_KEY }}
    
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ steps.app-token.outputs.token }}

    - name: Use Node.js 20.x
      uses: actions/setup-node@v2
      with:
        node-version: 20.x

    - name: Set Git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Tag the release with the version
      run: node ci --function tagRelease
      env:
        GH_TOKEN: ${{ steps.get_app_token.outputs.token }}