name: tag

on:
    push:
      branches:
        - master

jobs:
    tagVersion:
        runs-on: ubuntu-latest

        steps:
        - name: Tag the release with the version
          run: node ci --function tagRelease
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}